# Generated by Django 3.1.5 on 2021-09-28 15:38

import apps.core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', apps.core.models.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='phone number should exactly be in 10 digits', regex='^\\d{10}$')])),
                ('type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Seller', 'SELLER'), ('Customer', 'CUSTOMER')], default=[], max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenderFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SellerAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.CharField(max_length=10)),
                ('warehouse_location', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('LABONE', 'Label One'), ('LABTWO', 'Label Two'), ('LABTHR', 'Label Three'), ('LABFOU', 'Label Four'), ('LABFIV', 'Label Five'), ('LABSIX', 'Label Six'), ('LABSEV', 'Label Seven')], default='LABONE', max_length=6)),
                ('product_category', models.CharField(choices=[('Upper-body', (('JACPAR', 'Parka'), ('JACCOA', 'Coat'), ('JACJAC', 'Jacket'), ('SWESWE', 'Sweatshirt'), ('SWEHOO', 'Hoodie'), ('SHILON', 'Long Sleeve Shirt'), ('SHISHO', 'Short Sleeve Shirt'), ('TSHLON', 'Long Sleeve T-Shirt'), ('TSHSHO', 'Short Sleeve T-Shirt'), ('TSHPOL', 'Polo Shirt'))), ('Lower-body', (('PANJEA', 'Jeans'), ('PANCAR', 'Cargo'), ('PANCHI', 'Chino'), ('PANSHO', 'Shorts'), ('DREDRE', 'Dress'), ('DRESKI', 'Skirt'))), ('Accesories', (('ACCBEA', 'Beanie'), ('ACCCAP', 'Cap'), ('ACCBAG', 'Bag'), ('ACCBEL', 'Belt'), ('ACCWAL', 'Wallet'), ('ACCSUN', 'Sunglasses'), ('ACCSWI', 'Swimsuit'), ('ACCJEW', 'Jewelry')))], default='JACPAR', max_length=6)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('NA', 'Not Applicable'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='NA', max_length=3)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/')),
                ('quantity', models.IntegerField(default=1)),
                ('person_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genderfilter')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=42)),
                ('street_address_1', models.CharField(max_length=32)),
                ('street_address_2', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=24)),
                ('postcode', models.CharField(max_length=12)),
                ('county', models.CharField(max_length=24)),
                ('country', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
