# Generated by Django 3.1.5 on 2021-09-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_orderlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='street_address_2',
        ),
    ]
